name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd frontend
          npm install
          npm run build
        env:
          VITE_APP_API_BASE_URL: ${{ secrets.VITE_APP_API_BASE_URL }}

      - name: Deploy
        uses: JinhaKimGH/github-pages-deploy-action@v3 # Deploy action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authentication token to push to GitHub
          BRANCH: gh-pages # Target branch for GitHub Pages
          FOLDER: frontend/build # Folder to deploy (make sure this is the correct folder)
